version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0
      - image: mongo:3.6.8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/shopping_basket_api

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm rebuild

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: Run Tests
          command: |
            # notify Code Climate of a pending test report using `before-build`
            # run the tests
            npm run test
            # upload the report
